USE tql_store_saas;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS integration_hll_shop (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    external_shop_id VARCHAR(64) NOT NULL COMMENT '哗啦啦门店ID',
    external_group_id VARCHAR(64) DEFAULT NULL COMMENT '哗啦啦集团ID',
    external_shop_code VARCHAR(64) DEFAULT NULL COMMENT '哗啦啦组织编码',
    shop_name VARCHAR(160) NOT NULL COMMENT '门店名称',
    brand_id VARCHAR(64) DEFAULT NULL COMMENT '哗啦啦品牌ID',
    brand_name VARCHAR(160) DEFAULT NULL COMMENT '品牌名称',
    business_model VARCHAR(32) DEFAULT NULL COMMENT '业务模式',
    operation_mode VARCHAR(32) DEFAULT NULL COMMENT '运营模式',
    business_status VARCHAR(32) DEFAULT NULL COMMENT '门店营业状态',
    city_code VARCHAR(32) DEFAULT NULL COMMENT '城市编码',
    city_name VARCHAR(64) DEFAULT NULL COMMENT '城市名称',
    address VARCHAR(255) DEFAULT NULL COMMENT '门店详细地址',
    shop_phone VARCHAR(32) DEFAULT NULL COMMENT '门店联系电话',
    shop_open_time VARCHAR(64) DEFAULT NULL COMMENT '门店营业时间',
    image_path VARCHAR(500) DEFAULT NULL COMMENT '门店图片路径',
    longitude DECIMAL(10, 6) DEFAULT NULL COMMENT '百度地图经度',
    latitude DECIMAL(10, 6) DEFAULT NULL COMMENT '百度地图纬度',
    record_action VARCHAR(32) DEFAULT NULL COMMENT '第三方记录状态',
    source_create_time DATETIME DEFAULT NULL COMMENT '第三方记录创建时间',
    source_update_time DATETIME DEFAULT NULL COMMENT '第三方记录修改时间',
    raw_json JSON NOT NULL COMMENT '第三方门店原始JSON数据',
    last_sync_task_id BIGINT NOT NULL COMMENT '最后同步任务ID',
    last_sync_time DATETIME NOT NULL COMMENT '最后同步时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标志：0未删除，1已删除',
    create_by BIGINT DEFAULT NULL COMMENT '创建人用户ID',
    update_by BIGINT DEFAULT NULL COMMENT '更新人用户ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_integration_hll_shop (tenant_id, external_shop_id),
    KEY idx_integration_hll_shop_group (tenant_id, external_group_id),
    KEY idx_integration_hll_shop_code (tenant_id, external_shop_code),
    KEY idx_integration_hll_shop_brand (tenant_id, brand_id),
    KEY idx_integration_hll_shop_status (tenant_id, business_status, deleted),
    KEY idx_integration_hll_shop_task (tenant_id, last_sync_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='哗啦啦门店数据镜像表';
