USE tql_store_saas;

CREATE TABLE IF NOT EXISTS tql_food (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    isActive VARCHAR(16) NULL,
    foodCode VARCHAR(128) NOT NULL,
    foodName VARCHAR(255) NOT NULL,
    foodCategoryKey VARCHAR(128) NULL,
    foodCategoryCode VARCHAR(128) NULL,
    foodCategoryName VARCHAR(255) NULL,
    foodType VARCHAR(64) NULL,
    foodID BIGINT NOT NULL,
    groupID VARCHAR(128) NULL,
    shopID BIGINT NOT NULL,
    departmentID VARCHAR(128) NULL,
    parentFoodID VARCHAR(128) NULL,
    isOpen VARCHAR(16) NULL,
    isNews VARCHAR(16) NULL,
    isTempFood VARCHAR(16) NULL,
    isSetFood VARCHAR(16) NULL,
    foodMnemonicCode VARCHAR(128) NULL,
    origin VARCHAR(64) NULL,
    tagId VARCHAR(128) NULL,
    areaTagName VARCHAR(255) NULL,
    actionTime VARCHAR(64) NULL,
    createTime DATETIME NULL,
    dr CHAR(1) NOT NULL DEFAULT '0',
    sync_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tql_food_source (tenant_id, shopID, foodID),
    KEY idx_tql_food_query (tenant_id, shopID, foodCode, dr),
    KEY idx_tql_food_name (tenant_id, shopID, foodName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tql_dish_bom (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    type INT NULL,
    food_id VARCHAR(128) NOT NULL,
    food_name VARCHAR(255) NULL,
    food_code VARCHAR(128) NOT NULL,
    price DECIMAL(18,6) NULL,
    cost DECIMAL(18,6) NULL,
    gross_profit DECIMAL(18,6) NULL,
    gross_profit_rate DECIMAL(18,6) NULL,
    verifier_status INT NOT NULL DEFAULT 0,
    verifier_time DATETIME NULL,
    verifier_refuse_reason VARCHAR(500) NULL,
    verifier VARCHAR(128) NULL,
    submit_by VARCHAR(128) NULL,
    submit_time DATETIME NULL,
    shop_id BIGINT NOT NULL,
    dept_code VARCHAR(128) NOT NULL,
    dept_name VARCHAR(255) NULL,
    bom_version VARCHAR(64) NULL,
    bom_effective_time DATETIME NULL,
    bom_failure_time DATETIME NULL,
    is_lock INT NOT NULL DEFAULT 0,
    is_enable INT NOT NULL DEFAULT 1,
    revision INT NOT NULL DEFAULT 1,
    unit_id BIGINT NULL,
    unit VARCHAR(64) NULL,
    product_coefficient DECIMAL(18,6) NULL,
    remark VARCHAR(500) NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    dr CHAR(1) NOT NULL DEFAULT '0',
    del CHAR(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (id),
    KEY idx_tql_dish_bom_food (tenant_id, shop_id, food_code, dept_code, del),
    KEY idx_tql_dish_bom_status (tenant_id, verifier_status, is_enable, del)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tql_bom (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    type INT NULL,
    stap_id BIGINT NULL,
    stap_code VARCHAR(128) NOT NULL,
    stap_name VARCHAR(255) NULL,
    unit VARCHAR(64) NULL,
    accunit VARCHAR(64) NULL,
    quota DECIMAL(18,6) NOT NULL,
    accquota DECIMAL(18,6) NULL,
    cost DECIMAL(18,6) NULL,
    price DECIMAL(18,6) NULL,
    revision VARCHAR(64) NULL,
    stap_type VARCHAR(64) NULL,
    specification VARCHAR(255) NULL,
    woolen VARCHAR(255) NULL,
    net_delivery_rate VARCHAR(64) NULL,
    clean_material VARCHAR(255) NULL,
    dept_id BIGINT NULL,
    shop_id BIGINT NOT NULL,
    dept_code VARCHAR(128) NULL,
    dept_name VARCHAR(255) NULL,
    food_code VARCHAR(128) NOT NULL,
    del TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_tql_bom_dish (tenant_id, dish_id, del),
    KEY idx_tql_bom_material (tenant_id, shop_id, stap_code, del),
    CONSTRAINT fk_tql_bom_dish FOREIGN KEY (dish_id) REFERENCES tql_dish_bom(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
