USE tql_store_saas;
SET NAMES utf8mb4;

SELECT TABLE_NAME, TABLE_COMMENT
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND (TRIM(TABLE_COMMENT) = '' OR TABLE_COMMENT LIKE '%?%')
ORDER BY TABLE_NAME;

SELECT TABLE_NAME, COLUMN_NAME, COLUMN_COMMENT
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND (TRIM(COLUMN_COMMENT) = '' OR COLUMN_COMMENT LIKE '%?%')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

SELECT
    (SELECT COUNT(*)
     FROM information_schema.TABLES
     WHERE TABLE_SCHEMA = DATABASE()
       AND (TRIM(TABLE_COMMENT) = '' OR TABLE_COMMENT LIKE '%?%')) AS invalid_table_comments,
    (SELECT COUNT(*)
     FROM information_schema.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE()
       AND (TRIM(COLUMN_COMMENT) = '' OR COLUMN_COMMENT LIKE '%?%')) AS invalid_column_comments;
